apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: test-volume
      mountPath: /usr/share/nginx/html/test.html
      subPath: test.html
  volumes:
  - name: test-volume
    hostPath:
      path: /data
      type: Directory