apiVersion: v1
kind: Pod
metadata:
  name: two-container-pod
  labels:
    app: my-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
