apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  # namespace: frontend
  labels:
    app: my-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
