apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-2
  # namespace: backend
  labels:
    app: my-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
