apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-rolebinding
  namespace: default
subjects:
  - namespace: default
    kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: default-role
  apiGroup: rbac.authorization.k8s.io