apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: default
subjects:
  - namespace: default
    kind: User
    name: developer-be
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io