apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestar-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codestar-deployment
  template:
    metadata:
      labels:
        app: codestar-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.1
        ports:
        - containerPort: 80
